jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # ►►►  NEW STEP — copy the JSON into the built site  ◄◄◄
      - name: Copy data file to site root
        run: cp _data/Curated_POMs.json _site/Curated_POMs.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
